### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by shilenkoalexander** [jenekL/diploma#1]
Hello Evgeniy. 
I faced with a big problem while reading your code.
I'm not sure if you noticed it, but its written on C#. 
If you don't fix it to Java I will have to unsubscribe. Sorry

**Comment by jenekL** [comment]
@Whiner Hello Alexander! 

That was a big mistake that you've seen my diploma, it was hidden for a very long time, but the situation of the past months forced me to make it public.

Rewriting it on Java will be a big work, probably I'll need help with that. Do you have a couple of hundreds of free hours right now? If yes - do not hesitate to DM me, and we can come up with good solutions together!

Best regards and with tons of love,
Yevhen

**Comment by shilenkoalexander** [comment]
Dear Yevhen,

I have all time of the eternity for you.

Best regards,
Alexander
